name: dayfi
description: "Dayfi - Your digital financial companion"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

  # State management and async
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  dio: ^5.4.0
  gap: ^3.0.1
  device_info_plus: ^9.0.3
  flutter_screenutil: ^5.9.3
  get_it: ^8.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_crashlytics: ^5.0.1
  flutter_local_notifications: ^17.2.1
  path_provider: ^2.1.5
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.1
  pinput: ^5.0.2
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  flutter_animate: ^4.5.0
  another_flushbar: ^1.12.32
  local_auth: ^2.3.0
  connectivity_plus: ^6.0.5
  uuid: ^4.5.1
  intercom_flutter: ^9.4.9
  loading_animation_widget: ^1.3.0
  mixpanel_flutter: ^2.1.0
  smile_id: ^11.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.4.1
  flutter_launcher_icons: ^0.12.0

  # Code generation
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.1.0+1

flutter_gen:
  integrations:
    flutter_svg: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "Dayfi Test"
      android:
        applicationId: "com.dayfi.test"
      ios:
        bundleId: "com.dayfi.test"
        firebase:
          config: "firebase/GoogleService-Info-dev.plist"
    pilot:
      app:
        name: "Dayfi Pilot"
      android:
        applicationId: "com.dayfi.pilot"
      ios:
        bundleId: "com.dayfi.pilot"
        firebase:
          config: "firebase/GoogleService-Info-pilot.plist"
    prod:
      app:
        name: "Dayfi"
      android:
        applicationId: "com.dayfi.prod"
      ios:
        bundleId: "com.dayfi.prod"
        firebase:
          config: "firebase/GoogleService-Info-prod.plist"

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/pngs/
    - assets/icons/svgs/
    - assets/icons/svgs/world_flags/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # Custom fonts configuration
  fonts:
    - family: Readex Pro
      fonts:
        - asset: assets/fonts/ReadexPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
    - family: Youth
      fonts:
        - asset: assets/fonts/Youth-Thin.otf
          weight: 100
        - asset: assets/fonts/Youth-Light.otf
          weight: 300
        - asset: assets/fonts/Youth-Regular.otf
          weight: 400
        - asset: assets/fonts/Youth-Medium.otf
          weight: 500
        - asset: assets/fonts/Youth-Bold.otf
          weight: 700
        - asset: assets/fonts/Youth-Black.otf
          weight: 900

    - family: CabinetGrotesk
      fonts:
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Black.otf
          weight: 900
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Bold.otf
          weight: 700
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Extrabold.otf
          weight: 800
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Extralight.otf
          weight: 200
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Light.otf
          weight: 300
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Thin.otf
          weight: 100

    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-VariableFont_wght.ttf

    - family: Karla
      fonts:
        - asset: assets/fonts/karla/Karla-Regular.ttf
          weight: 400
        - asset: assets/fonts/karla/Karla-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/karla/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/karla/Karla-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/karla/Karla-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/karla/Karla-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/karla/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/karla/Karla-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/karla/Karla-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/karla/Karla-Light.ttf
          weight: 300
        - asset: assets/fonts/karla/Karla-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/karla/Karla-ExtraLightItalic.ttf
          weight: 200
          style: italic

    - family: Boldonse
      fonts:
        - asset: assets/fonts/boldonse.otf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 26

  # Android adaptive icons
#  adaptive_icon_foreground: "#5645F5"
  adaptive_icon_background: "#5645F5"

  # iOS options
  remove_alpha_ios: true
  background_color_ios: "#5645F5"
  image_path_ios: "assets/images/logo.png"
