name: dayfi
description: "Dayfi - Your digital financial companion"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  sign_in_with_apple: ^7.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

  # State management and async
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  dio: ^5.4.0
  gap: ^3.0.1
  device_info_plus: ^9.0.3
  package_info_plus: ^8.0.2
  flutter_screenutil: ^5.9.3
  get_it: ^8.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_crashlytics: ^5.0.1
  flutter_local_notifications: ^17.2.1
  path_provider: ^2.1.5
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.1
  pinput: ^5.0.2
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  flutter_animate: ^4.5.0
  another_flushbar: ^1.12.32
  local_auth: ^2.3.0
  connectivity_plus: ^6.0.5
  uuid: ^4.5.1
  intercom_flutter: ^9.4.9
  loading_animation_widget: ^1.3.0
  mixpanel_flutter: ^2.1.0
  url_strategy: ^0.2.0
  shimmer: ^3.0.0
  share_plus: ^10.1.2
  screenshot: ^3.0.0
  google_sign_in: ^6.2.1
  lottie: 
  firebase_storage: ^13.0.4
  # open_mail_app_plus: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.4.1
  flutter_launcher_icons: ^0.12.0

  # Code generation
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.1.0+1
  flutter_native_splash: ^2.4.7

flutter_gen:
  integrations:
    flutter_svg: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "Dayfi App"
      android:
        applicationId: "com.dayfi.test"
      ios:
        bundleId: "com.dayfi.test"
        firebase:
          config: "firebase/GoogleService-Info-dev.plist"
    pilot:
      app:
        name: "Dayfi App"
      android:
        applicationId: "com.dayfi.pilot"
      ios:
        bundleId: "com.dayfi.pilot"
        firebase:
          config: "firebase/GoogleService-Info-pilot.plist"
    prod:
      app:
        name: "Dayfi App"
      android:
        applicationId: "com.dayfi.prod"
      ios:
        bundleId: "com.dayfi.prod"
        firebase:
          config: "firebase/GoogleService-Info-prod.plist"

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/pngs/
    - assets/icons/svgs/
    - assets/icons/svgs/world_flags/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # Custom fonts configuration
  fonts:
        
    - family: Karla
      fonts:
        - asset: assets/fonts/karla/Karla-Regular.ttf
          weight: 400
        - asset: assets/fonts/karla/Karla-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/karla/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/karla/Karla-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/karla/Karla-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/karla/Karla-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/karla/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/karla/Karla-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/karla/Karla-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/karla/Karla-Light.ttf
          weight: 300
        - asset: assets/fonts/karla/Karla-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/karla/Karla-ExtraLightItalic.ttf
          weight: 200
          style: italic

    - family: FunnelDisplay
      fonts:
        - asset: assets/fonts/Funnel_Display/otf/FunnelDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/Funnel_Display/otf/FunnelDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/Funnel_Display/otf/FunnelDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/Funnel_Display/otf/FunnelDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/Funnel_Display/otf/FunnelDisplay-ExtraBold.otf
          weight: 800
      
    - family: Moco
      fonts:
        - asset: assets/fonts/Moco.ttf

    - family: TuskerGrotesk
      fonts:
        - asset: assets/fonts/tusker-grotesk-7800-super.otf

    - family: Boldonse
      fonts:
        - asset: assets/fonts/boldonse.otf

    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBLACKITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYTHINITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYULTRALIGHTITALIC.OTF
  
    - family: Chirp
      fonts:
        - asset: assets/fonts/chirp/Chirp Regular.otf
        - asset: assets/fonts/chirp/Chirp Regular.ttf
        - asset: assets/fonts/chirp/Chirp Regular.woff
        - asset: assets/fonts/chirp/Chirp Medium.otf
        - asset: assets/fonts/chirp/Chirp Medium.ttf
        - asset: assets/fonts/chirp/Chirp Medium.woff
        - asset: assets/fonts/chirp/Chirp Bold.otf
        - asset: assets/fonts/chirp/Chirp Bold.ttf
        - asset: assets/fonts/chirp/Chirp Bold.woff
        - asset: assets/fonts/chirp/Chirp Heavy.otf
        - asset: assets/fonts/chirp/Chirp Heavy.ttf
        - asset: assets/fonts/chirp/Chirp Heavy.woff


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 26

  # Android adaptive icons
#  adaptive_icon_foreground: "#5645F5"
  adaptive_icon_background: "#5645F5"

  # iOS options
  remove_alpha_ios: true
  background_color_ios: "#5645F5"
  image_path_ios: "assets/images/logo.png"
