name: dayfi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_nfc_kit: ^3.6.0
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: 
  intl: ^0.20.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  package_info_plus: ^8.1.2
  ndef: ^0.3.4
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  dio_retry_plus: ^2.0.8
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  ml_card_scanner: ^0.2.3
  lottie: ^3.3.1
  loading_indicator: ^3.1.1
  local_auth: ^2.3.0
  card_scanner: ^1.0.2
  fl_chart: ^1.0.0
  encrypt: ^5.0.3
  sqflite: ^2.4.2
  pull_to_refresh: ^2.0.0
  share_plus: ^11.0.0
  bcrypt: ^1.1.3
  flutter_animate: ^4.5.2
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_widget_from_html: ^0.17.1
  dotted_border: ^3.1.0
  qr_flutter: ^4.1.0
  
  # nfc_manager:

dev_dependencies:
  analyzer: ^7.7.1
  lints: ^6.0.0
  flutter_test:
    sdk: flutter
  drift_dev: ^2.22.1
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2
  stacked_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  # synthetic-package: false
  assets:
    - assets/
    - assets/cards/
    - assets/icons/
    - assets/html/
    - assets/images/
    - assets/svgs/
  fonts:

    - family: CabinetGrotesk
      fonts:
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Black.otf
          weight: 900
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Bold.otf
          weight: 700
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Extrabold.otf
          weight: 800
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Extralight.otf
          weight: 200
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Light.otf
          weight: 300
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/cabinet_grotesk/CabinetGrotesk-Thin.otf
          weight: 100

    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-VariableFont_wght.ttf

    - family: FatFrank
      fonts:
        - asset: assets/fonts/fonnts.com-FatFrank_Heavy.otf
    - family: Karla
      fonts:
        - asset: assets/fonts/karla/Karla-Regular.ttf
          weight: 400
        - asset: assets/fonts/karla/Karla-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/karla/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/karla/Karla-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/karla/Karla-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/karla/Karla-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/karla/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/karla/Karla-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/karla/Karla-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/karla/Karla-Light.ttf
          weight: 300
        - asset: assets/fonts/karla/Karla-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/karla/Karla-ExtraLightItalic.ttf
          weight: 200
          style: italic

    - family: Readex Pro
      fonts:
        - asset: assets/fonts/ReadexPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
    - family: Youth
      fonts:
        - asset: assets/fonts/Youth-Thin.otf
          weight: 100
        - asset: assets/fonts/Youth-Light.otf
          weight: 300
        - asset: assets/fonts/Youth-Regular.otf
          weight: 400
        - asset: assets/fonts/Youth-Medium.otf
          weight: 500
        - asset: assets/fonts/Youth-Bold.otf
          weight: 700
        - asset: assets/fonts/Youth-Black.otf
          weight: 900
    - family: Boldonse
      fonts:
        - asset: assets/fonts/boldonse.otf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 26

  # Android adaptive icons
#  adaptive_icon_foreground: "#5645F5"
  adaptive_icon_background: "#5645F5"

  # iOS options
  remove_alpha_ios: true
  background_color_ios: "#5645F5"
  image_path_ios: "assets/images/logo.png"
